# Generated by Django 5.2.1 on 2025-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('penthouse', 'Пентхаус'), ('duplex', 'Дуплекс'), ('loft', 'Лофт'), ('room', 'Комната'), ('maisonette', 'Мезонет'), ('bungalow', 'Бунгало'), ('townhouse', 'Таунхаус'), ('farmhouse', 'Фермерский дом'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('admin', 'Администратор')], default='tenant', max_length=20),
        ),
    ]
